name: UhcMeetup
version: 1.2
main: com.github.gonzq.uhcmeetup.UhcMeetup
api-version: 1.17
softdepend: [PlaceholderAPI]
author: ! Gonzq#4451
description: An UhcMeetup plugin for Minecraft 1.17.x
website: https://github.com/Gonzaa3007

commands:
  uhcmeetup:
  kt:
  scenarios:
    aliases: [scen]
  topstats:
  stats:
  vote:
  forcestart:
